✨(backend) implement addition operation for VideoDayViews class
openfun/warren pull request #22
Opened 2023-06-19 14:45 UTC by lebaudantoine

## Purpose

Add new functionnalities on `VideoDayViews` class and prevent potentiel issue on `VideoViews`.

## Proposal

Added `__add__` and `__radd__` methods to `VideoDayViews` class for left-sided or right-sided addition operations

In the `VideoViews` class, there was a potential issue where the total and daily_views attributes could become desynchronized, causing bugs. To address this, total is now a read-only property that is dynamically computed based on the daily_views value.

Minor improvement: The current implementation recomputes the `total` property every time its value is accessed, which may impact performance. To mitigate this, I propose using the `@cached_property` decorator, which computes the value only once. However, it is important to ensure that the cached value of `total` is updated whenever `daily_views` changes. I would address this improvement in a next PR.

2023-06-19 19:22 UTC, lebrunthibault requested changes

2023-06-19 19:22 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/api.py
> +    @property
Attention : properties are not serialized by pydantic and so total would be removed from the api response.
We could keep the normal total field and set it in the __init__ method
With pydantic v2 we would be able to use computed fields

2023-06-19 19:37 UTC, lebaudantoine commented on CHANGELOG.md
> +- Add addition on `VideoDayViews` class, prevent potential issue on `VideoViews`
Actually it is, using the `+` before with `VideoDayViews` would trigger an error.

2023-06-19 19:38 UTC, lebaudantoine commented on src/backend/plugins/video/warren_video/api.py
> +    @property
If we do what you suggest, we lose the interest of this PR:

2023-06-19 20:08 UTC, lebaudantoine commented on src/backend/plugins/video/warren_video/api.py
> +    @property
Two quick workarounds :

2023-06-20 10:09 UTC, lebrunthibault commented on CHANGELOG.md
> +- Add addition on `VideoDayViews` class, prevent potential issue on `VideoViews`
I'm not sure but I think it's meant to be from the api user perspective point of view (see for example : https://github.com/openfun/warren/pull/10#discussion_r1211651520, to be confirmed)

2023-06-20 10:22 UTC, lebaudantoine commented on CHANGELOG.md
> +- Add addition on `VideoDayViews` class, prevent potential issue on `VideoViews`
I think, what @jmaupetit meant was, changes on dev setup, docker setup, etc.. are not meant to be tracked in the changelog.
These changes add functionalities to the warren package, thus for the user using the package. Let's quickly double-check during the standup.

2023-06-20 10:22 UTC, lebaudantoine commented on src/backend/plugins/video/warren_video/api.py
> +    @property
What do you think about calling explicitly the property while returning the object @lebrunthibault?

2023-06-20 10:23 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/api.py
> +    @property
This idea is interesting I think we should keep it. The dict override might not solve the problem because it will not override the json() method (used for json serialization I think).
pydantic v2 would be great but I understand its not yet ready for production user.

I would consider a solution of this type :

```python
class Histogram(BaseModel):
    """Histogram over a day range."""

    day_totals: List[HistogramDay]
    total: int

    def __init__(self, **data):
        """Instantiate a histogram from a list of day totals."""
        data["total"] = 0

        super().__init__(**data)

        self.total = sum(day.total for day in self.day_totals)
```

or a factory method `make_histogram(days: List[HistogramDays]) -> Histogram` would also be possible but would make it possible to instantiate an unsynced Histogram by itself

2023-06-20 12:54 UTC, closed without merging