[WIP] ✨️(backend) add 2 endpoint parameters
openfun/warren pull request #35
Opened 2023-06-29 13:57 UTC by cyrillay

## Purpose

Add `unique` and `complete` endpoint parameters for counting completed video events and/or unique viewers

## Proposal

- [x] Add logic in the indicator 
- [ ] Test the new logic
- [ ] Test various parameters combination

2023-06-30 14:39 UTC, jmaupetit commented on src/backend/plugins/video/warren_video/indicators/daily_video_views.py
> +class DailyVideoViewsIndicator(BaseIndicator):
We already know that it's an indicator, it's not required to mention it as a suffix:

```suggestion
class DailyVideoViews(BaseIndicator):
```

2023-06-30 14:39 UTC, jmaupetit commented on src/backend/plugins/video/warren_video/indicators/daily_video_views.py
> +        is_completed_views: bool,
```suggestion
        is_completed: bool,
```

2023-06-30 14:39 UTC, jmaupetit commented on src/backend/plugins/video/warren_video/indicators/daily_video_views.py
As we still have few indicators, a single `indicators.py` file is preferred.

2023-07-04 09:52 UTC, cyrillay commented on src/backend/core/pyproject.toml
> +    "pandas==2.0.2",
Not sure why this appears, as it is already on main from the previous PR

2023-07-04 09:55 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +def parse_raw_statements(raw_statements):
Should this be defined inside the `BaseIndicator` class ? I did it this way first, but pycharm gives me a warning that I don't use the `self`, and so can define the method outside of the class

2023-07-04 09:56 UTC, cyrillay commented on src/backend/plugins/video/tests/test_api.py
> +    video_views = (Response[VideoViews]).parse_obj(response.json()).content
Those are changes from #34

2023-07-04 09:58 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +            filtered_view_duration.groupby(filtered_view_duration["date"])
Should this be factorized ? IMO, it shouldn't, as it is quite specific to those two indicators (for now), and it would add complexity to add a function that would essentially be a wrapper of the pandas methods, without added value.

2023-07-05 09:45 UTC, quitterie-lcs reviewed
<img src="https://media2.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif"/>

2023-07-05 09:45 UTC, quitterie-lcs commented on src/backend/plugins/video/warren_video/indicators.py
> +        """Fetches statements and domputes the current indicator.
```suggestion
        """Fetches statements and computes the current indicator.
```

2023-07-05 09:45 UTC, quitterie-lcs commented on src/backend/core/warren/base_indicator.py
> +def parse_raw_statements(raw_statements):
Otherwise, you can define it as a static method in the `BaseIndicator` class (using the `@staticmethod` decorator)

2023-07-05 13:10 UTC, lebrunthibault requested changes

2023-07-05 13:10 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +        # Filter out video played events before configured time threshold
```suggestion
        # Filter out video played events before the configured time threshold
```

2023-07-05 13:10 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +        # Apply the filtering function to each row and update the DataFrame in place
if the DataFrame is updated in place why is it assigned to `filter_view_duration` ?

2023-07-05 13:10 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +            .rename(columns={"id": "count"})
this part could maybe be split into another python statement ?

2023-07-05 13:10 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +        """Fetches statements and domputes the current indicator.
```suggestion
        """Fetches statements and computes the current indicator.
```

2023-07-05 14:57 UTC, wilbrdt reviewed
![Alt text](https://media.giphy.com/media/dhCx7EyeGYD7O/giphy.gif)

2023-07-05 14:57 UTC, wilbrdt commented on src/backend/plugins/video/warren_video/indicators.py
> +                subset="actor.account.name", inplace=True
We would have to check for the four [valid IFI](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2423-inverse-functional-identifier) an Actor can take:
- mbox
- mbox_sha1sum
- openid
- account

Is it planned for the future?

2023-07-05 14:57 UTC, wilbrdt commented on src/backend/plugins/video/warren_video/api.py
> +            is_unique_viewers=unique,
Voting for is_unique_views!

2023-07-05 17:12 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +def parse_raw_statements(raw_statements):
Thanks quitterie, I wasn't aware of this decorator. 

I think I agree with you @lebrunthibault, I thought the function could belong to the class as a static method, but in the end, this helper could be useful outside of indicators too, so I'll leave it oustide the class for now. Later on, we could add this function and other helpers in a `helpers.py` file.

2023-07-05 17:16 UTC, cyrillay commented on src/backend/core/warren/models.py
> +    """Enum for status types."""
The convention in python is to use `UPPER_CASE` for enum values, so I would prefer to keep them as is here (and eventually change them on ralph's side), see [here](https://docs.python.org/3/library/enum.html) and [here](https://stackoverflow.com/a/21359677) for reference

2023-07-05 17:20 UTC, cyrillay commented on src/backend/plugins/video/warren_video/api.py
> +        indicator = DailyVideoViews(
In terms of code readability, I don't like instantiating classes using a variable holding the class name, and not directly the class itself, especially to save a few lines only. Also, it could hurt the linting, as we can't know before runtime what class is instantiated (so the IDE can't say what arguments should be passed)

2023-07-05 17:23 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +        is_unique_viewers: bool,
Agreed !

2023-07-05 17:27 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +        # Apply the filtering function to each row and update the DataFrame in place
You're right, it wasn't done in place actually. Fixed it

2023-07-06 07:45 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +    def fetch_statements(self) -> List:
Interesting options. In my opinion, I prefer the third option with a type alias : 
```
XAPI_STATEMENT = Dict[str, Any]
and -> List[XAPI_STATEMENT]:
``` 

The reason is that it gives a clear idea of what is returned by the function (xAPI statements), while not having too much constraints on the schema.
I am not in favor of the latter option : if we evolve the schema on the LRS side, we need to update it on warren as well, and synchronize the release of the LRS with the update of this repo. IMO, this cross-repo dependency can cause a big overhead.

Do you agree in selecting the type alias option ?

2023-07-06 07:53 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +                subset="actor.account.name", inplace=True
Interesting, I wasn't aware of this. If I understand correctly, we could have statements that don't even have the `actor.account` field, but `actor.mbox`/`actor.mbox_sha1sum`/`actor.openid` (depending on `actor.objectType`) ?
I might have missed it because the sample data 2.1K statements I use all have `actor.name`, it's a good catch !

2023-07-10 14:45 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +    def fetch_statements(self) -> List:
Ok let's go for this !

2023-07-10 14:46 UTC, jmaupetit commented on src/backend/core/warren/base_indicator.py
> +def parse_raw_statements(raw_statements):
Using a class static method is a neat way to namespace a function, but it has to be related to the class. In this case a function looks perfectly fine to me. Maybe we will move its definition in an `utils.py`  module in a near future :man_shrugging:

2023-07-10 15:00 UTC, jmaupetit reviewed
<img src="https://media2.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif"/>

2023-07-10 15:58 UTC, jmaupetit commented on src/backend/plugins/video/warren_video/api.py
> +        indicator = DailyVideoViews(
Or:

```python
indicator_kwargs = {
    "client": lrs_client,
    "video_uuid": video_uuid,
    "date_range": DatetimeRange(since=filters.since, until=filters.until),
    "is_unique_views": unique,
}


indicator = DailyCompletedVideoViews(**indicator_kwargs) if complete else DailyVideoViews(**indicator_kwargs)
```

2023-07-11 08:44 UTC, cyrillay commented on src/backend/plugins/video/warren_video/api.py
> +        indicator = DailyVideoViews(
The only downside is that we loose the IDE validation on the existence/non existence of the parameters for the class 🤷  But I don't have a strong opinion here, so I change it for the first option. (Not the second one that overlaps the 90 characters line limit, and I don't think it's worth adding parenthesis just for the sake of having the ternary expression)

2023-07-11 09:14 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +                subset="actor.account.name", inplace=True
I developed a `add_unique_actor_id` utility method that adds a column `actor.unique_actor_id` so that future developers don't have to worry about the 4 IRIs and 4 ways of identification. This column is added as part of the pre processing of the statements obtained (after normalizing), so future indicators can choose on how to use it (`df.drop_duplicates(subset="actor.unique_actor_id", inplace=True`). What do you think ?

Also, we don't have a `Statements` class, do we ? Or do you mean `src.ralph.api.models.LaxStatement` ?
I don't think it's a good idea to enforce strong typing here : end users might use different LRS and slightly different schemas with different validation rules. Also, we create (increase?) the dependency to ralph LRS, in the same mind of this [comment](https://github.com/openfun/warren/pull/35#discussion_r1254063827). What do you think ?

2023-07-11 09:27 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +            client: The LRS backend from which the query is to be issued
what do you think ?

2023-07-11 09:27 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +        self.client = client
what do you think ?

2023-07-11 09:30 UTC, lebrunthibault commented
🎉

2023-07-11 09:46 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +        self.client = client
Sorry I had missed this comment ! 
I didn't make them private because accessing or modifying them even after the class instantiation doesn't cause any problem. Users of the class could change the `is_unique` or `video_uuid` property and perform the computation again 🤷

2023-07-11 10:03 UTC, lebrunthibault commented on src/backend/plugins/video/warren_video/indicators.py
> +        self.client = client
I see ! I think it's simpler to recreate objects than mutate existing ones for the logical flow but I don't have a strong a priori on this, we can leave it like this

2023-07-11 10:04 UTC, jmaupetit commented on src/backend/plugins/video/warren_video/indicators.py
> +        renamed_df = count_by_date.rename(columns={"id": "count"}).loc[:, ["date", "count"]]
Does the following work?

```suggestion
        count_by_date = (
            flattened.groupby(flattened["date"])
            .count()
            .reset_index()
            .rename(columns={"id": "count"}).loc[:, ["date", "count"]]
        )
```

2023-07-11 10:05 UTC, jmaupetit commented on src/backend/core/warren/base_indicator.py
> +    return statements
Also, we can call this field `actor.uuid` if you store the hex representation of the checksum.

2023-07-11 10:07 UTC, jmaupetit commented on src/backend/plugins/video/warren_video/indicators.py
> +                subset="actor.account.name", inplace=True
It's a good idea to add an actor "UUID" column and write an utility for this :+1: 

Types in my example was a way to auto-document my suggestion: we don't need to be too pedantic on this :wink:

2023-07-11 11:47 UTC, lebaudantoine commented on src/backend/plugins/video/warren_video/api.py
> +        indicator = DailyVideoViews(
`kwargs` is a clever approach that enhances code readability by explicitly highlighting that only the class changes between the `if` and `else` statements, while the arguments remain unchanged. This improvement makes it easier to understand the logic and flow of the code.

2023-07-11 11:48 UTC, lebaudantoine commented on src/backend/plugins/video/warren_video/api.py
> +        indicator = DailyVideoViews(
`kwargs` would enhance code readability by explicitly highlighting that only the class changes between the if and else statements, while the arguments remain unchanged.

2023-07-11 14:21 UTC, lebaudantoine commented on src/backend/core/warren/base_indicator.py
> +    columns_to_check = ["actor.account.name", "actor.account.homePage", "actor.mbox", "actor.openid"]
shouldn't it a be constant set? 
```suggestion
    COLUMNS_TO_CHECK = {"actor.account.name", "actor.account.homePage", "actor.mbox", "actor.openid"}
```

2023-07-11 14:27 UTC, lebaudantoine commented on src/backend/core/warren/base_indicator.py
> +            statements[column] = np.nan
```suggestion
    for missing_column in COLUMNS_TO_CHECK - set(statements.columns):
            statements[column] = np.nan
```

2023-07-11 14:43 UTC, lebaudantoine commented on src/backend/core/warren/base_indicator.py
> +            return row[non_nan_columns[0]]
Overall: I find unclear adding nan column, and then checking which columns are not nan. I would be more than happy to discuss it. Why not using set diff?

`non_nan_columns = COLUMNS_TO_CHECK - set(row.index)`

2023-07-11 14:58 UTC, lebaudantoine commented on src/backend/core/warren/base_indicator.py
> +            return row[non_nan_columns[0]]
This need to be tested, but some suggestions can be reused. I find it clearer to avoid nested `if`/`else`, it reduces cognitive complexity.

```suggestion
        non_nan_columns = COLUMNS_TO_CHECK - set(row.index)
        
        if not non_nan_columns:
                raise ValueError("No way of identifying the agent: all identification columns are NaN.")
        
        if len(non_nan_columns) == 1:
                return row[non_nan_columns[0]]

        if not {"actor.account.name", "actor.account.homePage"}.issubset(non_nan_columns):
                raise ValueError("Multiple ways of identification for agent: more than one identification column is filled.")

        return f"{row['actor.account.name']}-{row['actor.account.homePage']}"
```

2023-07-12 08:29 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +    return statements
Yes, that can work too. The only thing is I would need to do it before the parsing (because currently i denormalize the json as soon as possible to work with it, so the `actor` field result in multiple fields)

Also, we have something human readable that can still eventually be mapped to the original statements (I could improve the format of the `'actor.unique_actor_id'` so that we can know how it was identified before the creation of this column). In the `'actor.unique_actor_id'` field I could eventually store a JSON string of the original `actor` object ?

If we do the checksum, we can’t retrieve the original actor easily (not a huge deal)

WDYT ?

2023-07-12 08:32 UTC, cyrillay commented on src/backend/plugins/video/warren_video/indicators.py
> +        renamed_df = count_by_date.rename(columns={"id": "count"}).loc[:, ["date", "count"]]
Yes, it does, I had changed it because of @lebrunthibault [other comment](https://github.com/openfun/warren/pull/35#discussion_r1253087211) 😰 but I prefer to chain the operations so I will change it

2023-07-12 08:40 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +            statements[column] = np.nan
Okay, personally I find it harder to read and less natural, but I modify it

2023-07-12 08:41 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +def add_unique_actor_id(statements: pd.DataFrame) -> pd.DataFrame:
It's true that we uniform it, but I wanted to make it clear that we're adding a column here. Maybe `add_uniformized_actor_id` ?

2023-07-12 11:57 UTC, lebaudantoine commented on src/backend/core/warren/base_indicator.py
> +def add_unique_actor_id(statements: pd.DataFrame) -> pd.DataFrame:
True that my suggestion is missing the addition part, my bad. If you feel that `add_uniformized_actor_id` is fine let's go, however feel free to stick to your original naming 😁

2023-07-12 12:47 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +    columns_to_check = ["actor.account.name", "actor.account.homePage", "actor.mbox", "actor.openid"]
Yes, I agree. Pycharm gives a warning when defining a constant inside a function, but I think we should ignore it and follow the convention.

2023-07-12 12:49 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +def add_unique_actor_id(statements: pd.DataFrame) -> pd.DataFrame:
No no, naming is important and the last one is definitely better ;)

2023-07-12 14:51 UTC, jmaupetit commented on src/backend/core/warren/base_indicator.py
> +    }
I think we can make this a global `XAPI_ACTOR_IDENTIFIER_PATHS` configuration variable.

2023-07-12 14:51 UTC, jmaupetit commented on src/backend/core/warren/base_indicator.py
> +    )
I haven't tested it, but WDYT about the following alternative implementation?

```suggestion
    xapi_actor_identifier_columns = XAPI_ACTOR_IDENTIFIER_PATHS.intersection(set(statements.columns))
    
    if len(xapi_actor_identifier_columns) == 0:
        raise ValueError(
            "There is no way of identifying the agent in submitted statements."
        )

    statements["actor.uid"] = statements.apply(
        lambda row, columns: hashlib.sha256("-".join(row[columns]).hexdigest(), 
        axis=1, 
        xapi_actor_identifier_columns
    )
```

2023-07-12 14:51 UTC, jmaupetit commented on src/backend/core/warren/base_indicator.py
> +def add_uniformized_actor_id(statements: pd.DataFrame) -> pd.DataFrame:
I would prefer the following:

```suggestion
def add_actor_unique_id(statements: pd.DataFrame) -> pd.DataFrame:
```

2023-07-12 16:08 UTC, cyrillay commented on src/backend/core/warren/base_indicator.py
> +    )
Neat 🔥

2023-07-12 16:38 UTC, jmaupetit reviewed
I only have one minor remark :wink:

2023-07-12 19:13 UTC, jmaupetit approved these changes

2023-07-13 07:15 UTC, merged